foreground            #e2e2e2
background            #131313
selection_foreground  #1b1b1b
selection_background  #ffffff
url_color             #e2e2e2
cursor                #ffffff
cursor_text_color     #1b1b1b

color0   #131313
color1   #ffb4ab
color2   #ffffff
color3   #e2e2e2
color4   #ffffff
color5   #e2e2e2
color6   #919191
color7   #e2e2e2

color8   #919191
color9   #ffb4ab
color10  #ffffff
color11  #e2e2e2
color12  #ffffff
color13  #e2e2e2
color14  #919191
color15  #e2e2e2

tab_bar_background              #131313
tab_bar_margin_color            #131313
active_tab_foreground           #1b1b1b
active_tab_background           #ffffff
inactive_tab_foreground         #c6c6c6
inactive_tab_background         #131313
