foreground            #e5e2e2
background            #141314
selection_foreground  #2f3039
selection_background  #c6c5d2
url_color             #d4c1cb
cursor                #c6c5d2
cursor_text_color     #2f3039

color0   #141314
color1   #ffb4ab
color2   #c6c5d2
color3   #d4c1cb
color4   #c6c5d2
color5   #d4c1cb
color6   #d4c1cb
color7   #e5e2e2

color8   #919096
color9   #ffb4ab
color10  #c6c5d2
color11  #d4c1cb
color12  #c6c5d2
color13  #d4c1cb
color14  #b5a3ad
color15  #e5e2e2

tab_bar_background              #141314
tab_bar_margin_color            #141314
active_tab_foreground           #2f3039
active_tab_background           #c6c5d2
inactive_tab_foreground         #c8c5cc
inactive_tab_background         #141314
