-- Auto-generated by matugen via skwd-wall

local M = {}

M.base_30 = {
  white = "{{colors.on_background.default.hex}}",
  darker_black = "{{colors.surface_container_lowest.default.hex}}",
  black = "{{colors.surface.default.hex}}",
  black2 = "{{colors.surface_container_low.default.hex}}",
  one_bg = "{{colors.surface_container.default.hex}}",
  one_bg2 = "{{colors.surface_container_high.default.hex}}",
  one_bg3 = "{{colors.surface_container_highest.default.hex}}",
  grey = "{{colors.outline.default.hex}}",
  grey_fg = "{{colors.on_surface_variant.default.hex}}",
  grey_fg2 = "{{colors.outline.default.hex}}",
  light_grey = "{{colors.on_surface.default.hex}}",
  red = "{{colors.error.default.hex}}",
  baby_pink = "{{colors.error.default.hex}}",
  pink = "{{colors.tertiary.default.hex}}",
  line = "{{colors.surface_container.default.hex}}",
  green = "{{colors.primary.default.hex}}",
  vibrant_green = "{{colors.primary.default.hex}}",
  nord_blue = "{{colors.primary.default.hex}}",
  blue = "{{colors.primary.default.hex}}",
  seablue = "{{colors.primary.default.hex}}",
  yellow = "{{colors.secondary.default.hex}}",
  sun = "{{colors.secondary.default.hex}}",
  purple = "{{colors.tertiary.default.hex}}",
  dark_purple = "{{colors.tertiary.default.hex}}",
  teal = "{{colors.tertiary.default.hex}}",
  orange = "{{colors.tertiary.default.hex}}",
  cyan = "{{colors.tertiary.default.hex}}",
  statusline_bg = "{{colors.surface_container.default.hex}}",
  lightbg = "{{colors.surface_container_high.default.hex}}",
  pmenu_bg = "{{colors.primary_container.default.hex}}",
  folder_bg = "{{colors.primary_container.default.hex}}",
}

M.base_16 = {
  base00 = "{{colors.surface.default.hex}}",
  base01 = "{{colors.surface_container_low.default.hex}}",
  base02 = "{{colors.surface_container.default.hex}}",
  base03 = "{{colors.surface_container_high.default.hex}}",
  base04 = "{{colors.surface_container_highest.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.on_background.default.hex}}",
  base07 = "{{colors.on_surface.default.hex}}",
  base08 = "{{colors.error.default.hex}}",
  base09 = "{{colors.tertiary.default.hex}}",
  base0A = "{{colors.secondary.default.hex}}",
  base0B = "{{colors.primary.default.hex}}",
  base0C = "{{colors.tertiary.default.hex}}",
  base0D = "{{colors.primary.default.hex}}",
  base0E = "{{colors.tertiary.default.hex}}",
  base0F = "{{colors.error.default.hex}}",
}

M.polish_hl = {
  syntax = {},
  treesitter = {},
}

M.type = "dark"

M = require("base46").override_theme(M, "matugen")

return M
