[config]
mode = "dark"
type = "scheme-tonal-spot"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"
post_hook = "hyprctl reload"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.neovim]
input_path = "~/.config/skwd-wall/data/matugen/templates/nvim-theme.lua"
output_path = "~/.config/nvim/lua/themes/matugen.lua"
