-- Auto-generated by matugen via skwd-wall

local M = {}

M.base_30 = {
  white = "#e3e3dd",
  darker_black = "#0d0f0c",
  black = "#121411",
  black2 = "#1a1c19",
  one_bg = "#1e201d",
  one_bg2 = "#292b27",
  one_bg3 = "#333532",
  grey = "#8d9288",
  grey_fg = "#c3c8bd",
  grey_fg2 = "#8d9288",
  light_grey = "#e3e3dd",
  red = "#ffb4ab",
  baby_pink = "#ffb4ab",
  pink = "#96d0d7",
  line = "#1e201d",
  green = "#acd0a3",
  vibrant_green = "#acd0a3",
  nord_blue = "#acd0a3",
  blue = "#acd0a3",
  seablue = "#acd0a3",
  yellow = "#bccbb5",
  sun = "#bccbb5",
  purple = "#96d0d7",
  dark_purple = "#96d0d7",
  teal = "#96d0d7",
  orange = "#96d0d7",
  cyan = "#96d0d7",
  statusline_bg = "#1e201d",
  lightbg = "#292b27",
  pmenu_bg = "#3b5b37",
  folder_bg = "#3b5b37",
}

M.base_16 = {
  base00 = "#121411",
  base01 = "#1a1c19",
  base02 = "#1e201d",
  base03 = "#292b27",
  base04 = "#333532",
  base05 = "#e3e3dd",
  base06 = "#e3e3dd",
  base07 = "#e3e3dd",
  base08 = "#ffb4ab",
  base09 = "#96d0d7",
  base0A = "#bccbb5",
  base0B = "#acd0a3",
  base0C = "#96d0d7",
  base0D = "#acd0a3",
  base0E = "#96d0d7",
  base0F = "#ffb4ab",
}

M.polish_hl = {
  syntax = {},
  treesitter = {},
}

M.type = "dark"

M = require("base46").override_theme(M, "matugen")

return M
