-- Auto-generated by matugen via skwd-wall

local M = {}

M.base_30 = {
  white = "#e5e2e2",
  darker_black = "#0e0e0f",
  black = "#141314",
  black2 = "#1c1b1c",
  one_bg = "#201f20",
  one_bg2 = "#2a2a2a",
  one_bg3 = "#353435",
  grey = "#919096",
  grey_fg = "#c8c5cc",
  grey_fg2 = "#919096",
  light_grey = "#e5e2e2",
  red = "#ffb4ab",
  baby_pink = "#ffb4ab",
  pink = "#d4c1cb",
  line = "#201f20",
  green = "#c6c5d2",
  vibrant_green = "#c6c5d2",
  nord_blue = "#c6c5d2",
  blue = "#c6c5d2",
  seablue = "#c6c5d2",
  yellow = "#c8c5cb",
  sun = "#c8c5cb",
  purple = "#d4c1cb",
  dark_purple = "#d4c1cb",
  teal = "#d4c1cb",
  orange = "#d4c1cb",
  cyan = "#d4c1cb",
  statusline_bg = "#201f20",
  lightbg = "#2a2a2a",
  pmenu_bg = "#1c1d26",
  folder_bg = "#1c1d26",
}

M.base_16 = {
  base00 = "#141314",
  base01 = "#1c1b1c",
  base02 = "#201f20",
  base03 = "#2a2a2a",
  base04 = "#353435",
  base05 = "#e5e2e2",
  base06 = "#e5e2e2",
  base07 = "#e5e2e2",
  base08 = "#ffb4ab",
  base09 = "#d4c1cb",
  base0A = "#c8c5cb",
  base0B = "#c6c5d2",
  base0C = "#d4c1cb",
  base0D = "#c6c5d2",
  base0E = "#d4c1cb",
  base0F = "#ffb4ab",
}

M.polish_hl = {
  syntax = {},
  treesitter = {},
}

M.type = "dark"

M = require("base46").override_theme(M, "matugen")

return M
